name: Stage Storybook PR Checks
on:
  pull_request:
    branches:
      - master

env:
  PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}

jobs:
  smartui-gihub-action:
    name: Execute Storybook build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1

    - name: Find Last CommitId
      run: |
        API_HOST=https://api.github.com
        # Check out the PR branch
        git checkout $GITHUB_HEAD_REF
        # Get the commit ID of the last commit
        COMMIT_ID=$(git rev-parse HEAD)
        echo "Last commit ID of PR: $COMMIT_ID"
        GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
        echo "GITHUB_URL: $GITHUB_URL"
        echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV
   
    - name: setting node --version
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: |
        npm install
        
    - name: Check out other repo
      uses: actions/checkout@v3
      with:
          repository: LambdaTest/smartui-storybook
          ref: stage
          
    - name: Create storybook static build
      run: | 
        echo $pwd

    - name: Execute storybook build
      run: |
        npm -v
        node -v
        npm install commander --save
        node index.js storybook ./storybook-static --env stage
